# Generated by Django 5.1.4 on 2026-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="gas_dripped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
